version: '3.7'
services: 
    config-server:
      image: config-server:v2
      ports:
        - "8888:8888"
      restart: always
      networks: 
        - springcloud
    eureka-server: 
      image: eureka-server:v1
      ports: 
        - "8761:8761"
      restart: always
      networks: 
        - springcloud
    springcloudmysql: 
        image: mysql:8
        ports: 
            - "3306:3306"
        restart: always
        networks: 
            - springcloud
        environment:    
          MYSQL_DATABASE: db_springboot_cloud
          MYSQL_ROOT_PASSWORD: toor
    servico-produtos: 
      image: servico-produtos:v3
      restart: always
      networks: 
        - springcloud
      depends_on: 
        - config-server
        - eureka-server
        - springcloudmysql
networks: 
    springcloud:
